### ISSUE TITLE
[BUG]  Error Message  "> not supported between instance of NoneType and uint32"

### ISSUE THREAD

**Issue by lifeline143** [ChainGreenOrg/chaingreen-blockchain#31]
Every few minutes the attached error message pops up

![image](https://user-images.githubusercontent.com/85137470/122207730-0cb45e80-ce68-11eb-8143-033ae8eca9e5.png)

'>' not support between instance of 'NoneType' and 'uint32'     It has an OK button on it, and hitting it will close the message.

It will keep popping up and after a while appears to hang the GUI.
[debug.log](https://github.com/ChainGreenOrg/chaingreen-blockchain/files/6662486/debug.log)

**To Reproduce**

Connect to Chaingreen Blockchain
Wait
Not consistent error

**Expected behavior**
No error message

**Desktop (please complete the following information):**

- OS: Win10
- CPU: i7-4790K
[debug.log](https://github.com/ChainGreenOrg/chaingreen-blockchain/files/6662480/debug.log)

**Additional context**

**Comment by SparXalt** [comment]
I get the same error on launching in Ubuntu. Blew out my debug log and caught just this
`2021-06-16T09:51:39.221 farmer farmer_server              : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8778}
2021-06-16T09:51:39.258 harvester chaingreen.harvester.harvester: WARNING  Not farming any plots on this harvester. Check your configuration.
2021-06-16T09:51:44.016 full_node full_node_server        : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8777}
2021-06-16T09:51:44.297 full_node full_node_server        : WARNING  Connecting peer {'host': '127.0.0.1', 'port': 8749}
2021-06-16T09:51:47.462 wallet chaingreen.rpc.rpc_server  : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/sparxalt/chaingreen-blockchain/chaingreen/rpc/rpc_server.py", line 212, in safe_handle
    response = await self.ws_api(message)
  File "/home/sparxalt/chaingreen-blockchain/chaingreen/rpc/rpc_server.py", line 203, in ws_api
    return await f(data)
  File "/home/sparxalt/chaingreen-blockchain/chaingreen/rpc/wallet_rpc_api.py", line 931, in get_farmed_amount
    if height > last_height_farmed:
TypeError: '>' not supported between instances of 'NoneType' and 'uint32'

2021-06-16T09:51:56.454 wallet chaingreen.rpc.rpc_server  : WARNING  Error while handling message: Traceback (most recent call last):
  File "/home/sparxalt/chaingreen-blockchain/chaingreen/rpc/rpc_server.py", line 212, in safe_handle
    response = await self.ws_api(message)
  File "/home/sparxalt/chaingreen-blockchain/chaingreen/rpc/rpc_server.py", line 203, in ws_api
    return await f(data)
  File "/home/sparxalt/chaingreen-blockchain/chaingreen/rpc/wallet_rpc_api.py", line 931, in get_farmed_amount
    if height > last_height_farmed:
TypeError: '>' not supported between instances of 'NoneType' and 'uint32'`

**Comment by lifeline143** [comment]
That is exactly what shows up in my debug logs as well

**Comment by lifeline143** [comment]
FYI this bug is still present in 1.2.0

**Comment by decisev** [comment]
Hello I am also getting same bug. As an addition to the issue, the "CGN Total Farmed, CGN Block Rewards, CGN User Transaction Fees, and Last Height Farmed" boxes under the Farming tab are all blank while this error is occurring.

**Comment by rhernaus** [comment]
Somehow the code hits `Return None` on line 61 in chaingreen/wallet/transaction_record.py. If you change line 61 to `Return uint32(block_index)` it will "work". I haven't figured out yet what the exact cause is.

**Comment by wolfrage76** [comment]
> Somehow the code hits `Return None` on line 61 in chaingreen/wallet/transaction_record.py. If you change line 61 to `Return uint32(block_index)` it will "work".

Confirmed
