### ISSUE TITLE
[BUG]stopping services or restarting results in error on UPNP

### ISSUE THREAD

**Issue by bithadder** [ChainGreenOrg/chaingreen-blockchain#65]
**Describe the bug**
Restarting or stopping services result in an error but the services keeps running

**To Reproduce**
both

```
chaingreen start farmer -r
chaingreen stop all
```
will result in the error

**Expected behavior**
farmer restarts and services restarts without any problems

- OS: Linux
- OS Version/Flavor: Ubuntu Server 20.04 LTS
- CPU: Ryzen 3 2200G

**Additional context**
```

chaingreen start farmer -r
chaingreen_harvester: Traceback (most recent call last):
  File "/home/user/chaingreen-blockchain/venv/bin/chaingreen_harvester", line 33, in <module>
    sys.exit(load_entry_point('chaingreen-blockchain', 'console_scripts', 'chaingreen_harvester')())
  File "/home/user/chaingreen-blockchain/chaingreen/server/start_harvester.py", line 53, in main
    return run_service(**kwargs)
  File "/home/user/chaingreen-blockchain/chaingreen/server/start_service.py", line 246, in run_service
    return asyncio.run(async_run_service(*args, **kwargs))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/chaingreen-blockchain/chaingreen/server/start_service.py", line 240, in async_run_service
    return await service.run()
  File "/home/user/chaingreen-blockchain/chaingreen/server/start_service.py", line 163, in run
    await self.wait_closed()
  File "/home/user/chaingreen-blockchain/chaingreen/server/start_service.py", line 231, in wait_closed
    if self.upnp is not None:
AttributeError: 'Service' object has no attribute 'upnp'

```

**Comment by miosukakura** [comment]
Already fixed on the latest main branch. Thanks for the report. It will be released with release 1.2.2 or 2.0.0.
